name: Create Draft Release for dot org repo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: mv temp_dir yt-for-wp

    - name: Zip the folder
      run: |
        zip -r yt-for-wp-dot-org-${{ github.event.inputs.tag }}.zip yt-for-wp \
        -x "*.git/*" "*.github/*" \
        "yt-for-wp/package.json" \
        "yt-for-wp/package-lock.json" \
        "yt-for-wp/src/*" \
        "yt-for-wp/node_modules/*" \
        "yt-for-wp/.gitignore" \
        "yt-for-wp/webpack.config.js" \
        "yt-for-wp/github-update.php"

    - name: Create Draft Release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ github.event.inputs.tag }}
        draft: true
        prerelease: false # Set to true if this is a pre-release
        name: "Draft Release for YT for WP ${GITHUB_EVENT_INPUTS_TAG}" # Optional release name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: yt-for-wp-dot-org-${{ github.event.inputs.tag }}.zip
        asset_name: yt-for-wp-dot-org-${{ github.event.inputs.tag }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
