name: Create Separate Draft Release for dot org repo

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
      is_draft:
        description: 'Create as Draft Release (true/false)'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: mv temp_dir yt-for-wp

    - name: Zip the folder
      run: |
        zip -r yt-for-wp-dot-org-${{ github.event.inputs.tag }}.zip yt-for-wp \
        -x "*.git/*" "*.github/*" \
        "yt-for-wp/package.json" \
        "yt-for-wp/package-lock.json" \
        "yt-for-wp/src/*" \
        "yt-for-wp/node_modules/*" \
        "yt-for-wp/.gitignore" \
        "yt-for-wp/webpack.config.js" \
        "yt-for-wp/github-update.php"

    - name: Create Separate Draft Release
      uses: actions/create-release@v1
      with:
        tag_name: dot-org-${{ github.event.inputs.tag }}
        release_name: WordPress.org Release - ${{ github.event.inputs.tag }}
        body: |
          This release is prepared for WordPress.org submission and excludes files meant for development.
        draft: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: yt-for-wp-dot-org-${{ github.event.inputs.tag }}.zip
        asset_name: yt-for-wp-dot-org-${{ github.event.inputs.tag }}.zip
        asset_content_type: application/zip

permissions:
  contents: write
