name: Create Release for YouTube Free

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: mv temp_dir youtube-for-wordpress

    - name: Zip the folder
      run: |
        zip -r youtube-for-wordpress-${{ github.event.inputs.tag }}.zip youtube-for-wordpress \
        -x "*.git/*" "*.github/*" \
        "youtube-for-wordpress/package.json" \
        "youtube-for-wordpress/package-lock.json" \
        "youtube-for-wordpress/src/*" \
        "youtube-for-wordpress/node_modules/*" \
        "youtube-for-wordpress/.gitignore" \
        "youtube-for-wordpress/webpack.config.js"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: youtube-for-wordpress-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
