name: Create Release for YouTube Free

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: mkdir temp_dir

    - name: Copy files to temporary directory
      run: |
        find . -maxdepth 1 -not -name 'temp_dir' -not -name '.' -not -name '.git' -not -name '.github' -exec cp -r {} temp_dir/ \;

    - name: Rename directory
      run: mv temp_dir toolkit-integration-for-youtube

    - name: Zip the folder
      run: |
        zip -r toolkit-integration-for-youtube-${{ github.event.inputs.tag }}.zip toolkit-integration-for-youtube \
        -x "*.git/*" "*.github/*" \
        "yt-for-wp/package.json" \
        "yt-for-wp/package-lock.json" \
        "yt-for-wp/src/*" \
        "yt-for-wp/node_modules/*" \
        "yt-for-wp/.gitignore" \
        "yt-for-wp/webpack.config.js"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: yt-for-wp-${{ github.event.inputs.tag }}.zip
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
